# Site settings
title: Bay Area Cats
email: info@bayareacats.org
description: > # this means to ignore newlines until "baseurl:"
  A compilation of resources and veterinary support for trapping feral
  and community cats for trap-neuter-return (TNR). Includes instructions on how and where to get traps in
  the Santa Clara County in California.
baseurl: ""
url: "vanessaforney.github.io"

# Build settings
markdown: kramdown
