# Site settings
title: Cupertino Cats
email: cupertinocats@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A compilation of resources, rescue organizations, and veterinary support for trapping feral
  cats and rescuing kittens. Includes detailed instructions on how and where to get traps in 
  the South Bay Area in California. Find suggestions for low cost veterinary services including
  spay/neuter and vaccinations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cupertinocats.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
